version: '3.8'
services:
  mongodb:
    image: mongo:6
    container_name: nestjs_prod_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_prod:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: '$Admin@_1234$'
      MONGO_INITDB_DATABASE: nestgql_prod

  nestjs-app:
    build: .
    container_name: nestjs_prod_app
    restart: always
    depends_on:
      - mongodb
    ports:
      - "3002:3000"
    environment:
      DATABASE_URL: mongodb://localhost:27017/nestgql_prod?directConnection=true&authSource=admin&replicaSet=replicaset&retryWrites=true
    env_file:
      - .env.production
    command: ["npm", "run", "start:prod"]

volumes:
  mongodb_data_prod:
